---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Article2_Table3/BMP_Table3.xlsx
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/102716/articles/173986/master/folder/figures/Article2_Table3"
    treatFirstLineAsHeader: true
    fontSize: small
    url: "/users/102716/articles/173986/master/file/figures/Article2_Table3/BMP_Table3.xlsx"
