---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/cvBg/cvBg(1).png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/102716/articles/173986/master/folder/figures/cvBg"
    url: "/users/102716/articles/173986/master/file/figures/cvBg/cvBg(1).png"
